name: PR Update

on:
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Unit Tests
    uses: ./.github/workflows/test.yml
    secrets: inherit

  lint:
    name: Run Linters
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  build:
    name: Build Formbricks-web
    uses: ./.github/workflows/build-web.yml
    secrets: inherit

  docs:
    name: Build Docs
    uses: ./.github/workflows/build-docs.yml
    secrets: inherit

  e2e-test:
    name: Run E2E Tests
    uses: ./.github/workflows/e2e.yml
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}

  required:
    name: PR Check Summary
    needs: [lint, test, build, e2e-test, docs]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: fail if conditional jobs failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')
        run: exit 1
